name: Lint Checker

on:
    push:
        branches: ['master']
    pull_request:
        # The branches below must be a subset of the branches above
        branches: ['master']
    schedule:
        - cron: '15 23 * * 0'

jobs:
    eslint:
        name: Run eslint scanning
        runs-on: ubuntu-latest
        permissions:
            contents: read
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install ESLint
              run: |
                  npm install eslint@8.57.0
                  npm install @microsoft/eslint-formatter-sarif@2.1.7

            - name: Run ESLint
              run:
                  npx eslint .
                  --config eslint.config.mjs
                  #   --c .js,.jsx,.ts,.tsx
              continue-on-error: false
